# Development Override for Docker Compose
# ======================================
# This file automatically applies when running docker-compose up
# Provides hot-reload and development-friendly settings

version: '3.8'

services:
  weather-api:
    build:
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    command: ["uvicorn", "src.api.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  weather-dashboard:
    build:
      target: development
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: ["streamlit", "run", "src/dashboard/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
