[workspace]
authors = ["Jainam1673"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "🔥 Mojo Weather Data Pipeline"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# Development tasks
dev = "pixi shell"
install = "echo 'Dependencies installed via pixi'"

# Pipeline management
start-pipeline = { depends-on = ["init-db", "start-api", "start-ui"] }

# Data processing tasks
test-mojo = "mojo data_processor.mojo"
generate-data = "python -c 'import requests; requests.post(\"http://localhost:8000/generate-data\", json={\"num_points\": 1000})'"

# Server tasks
start-api = "uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
start-ui = "streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"

# Database tasks
init-db = "python database.py"
reset-db = "rm -f weather_data.db && python database.py"

# Testing and health
health-check = "curl -s http://localhost:8000/health | python -m json.tool"
test-api = "curl -s http://localhost:8000/ | python -m json.tool"

# Cleanup tasks
clean-logs = "rm -rf logs/*.log"
clean-data = "rm -f weather_data.db"
clean-all = { depends-on = ["clean-logs", "clean-data"] }

[dependencies]
mojo = ">=25.6.0.dev2025090305,<26"
python = ">=3.11"
fastapi = "*"
uvicorn = "*"
streamlit = "*"
pandas = "*"
numpy = "*"
plotly = "*"
requests = "*"
python-multipart = "*"
pydantic = "*"
scipy = "*"
